### ISSUE TITLE
Specify namespace for module to work

### ISSUE THREAD

**Issue by Wernervdmerwe** [desalvo/puppet-fail2ban#4]
I receive the following error:
SERVER: Could not find parent resource type '::params' of type hostclass

I had to change  "inherits params" to  "inherits fail2ban::params" in init.pp for the module to work

**Comment by desalvo** [comment]
Thanks, I'll fix it. Are you using puppet 4? I do not see this problem 
with puppet 3.
I'll fix this and another small issue I found in the next release.
Cheers,

```
 Alessandro
```

Il 18/01/16 21:37, Wernervdmerwe ha scritto:

**Comment by Wernervdmerwe** [comment]
Hi - yup, puppet 4

**Comment by desalvo** [comment]
OK, thanks, fixed in the master branch already.

**Comment by Wernervdmerwe** [comment]
Awesome. Only other change I had to make was in params, changing the ignoreip setting from ['127.0.0.1'] to '127.0.0.1'. 
Not sure if this is a fail2ban issue or a CentOS 7 one.

**Comment by alexandernilsson** [comment]
Are you planning on rolling out a new release with this fix to puppet forge?

**Comment by desalvo** [comment]
I should release a new version in puppet forge today with a lot of fixes.

**Comment by desalvo** [comment]
Released as version 1.0.0
